version: "3"
services:
    client:
        container_name: client
        build: ./client
        restart: always
        command: npm run start
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
        environment:
            - CHOKIDAR_USEPOLLING=true
    server:
        container_name: server
        build: ./
        restart: always
        command: npm run server
        ports:
            - "5000:5000"
        volumes:
            - ./:/server
            - /server/node_modules
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        expose:
            - "27017"
        restart: always
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
    adminmongo:
        container_name: adminmongo
        image: mrvautin/adminmongo
        ports:
            - 1234:1234
        environment:
            - HOST=0.0.0.0
volumes:
    mongodata: